<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Job Direct 3 - Enterprise</title>
<meta name="description" content="" />
<meta charset="utf-8">
<link href="/css/resetpwd.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/password-validater.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
				
		$('#reset_Submit').click(function(){
			var pwd   = $('#pwd').val().trim();
			var repwd = $('#repwd').val();

			checkUserPwd      = checkUserPassword(pwd);
			checkValidUserPwd = checkValidUserPassword(pwd);

			$(".error").html('');
			if(pwd==""){
				$(".error").html("Password should not be empty.");
				$(".error").css('color','#d41812');
				return false;
			} else if (!checkUserPwd.status) {
				$(".error").html(checkUserPwd.msg);
				$(".error").css('color','#d41812');

				return false;
			} else if (!checkValidUserPwd.status) {
				$(".error").html(checkValidUserPwd.msg);
				$(".error").css('color','#d41812');

				return false;
			} else if ( pwd == repwd ) {
				$.post('/index/resettingpwd',$("#reset_form").serialize(),function(data){
					var obj = jQuery.parseJSON(data);
					$("#reset_form").hide();
					$(".msg").html(obj.msg+'<br/> Redirecting to Login Page');
					$(".msg").css('color','#006400');

					setTimeout(function() {
						document.location.href='/';
					}, 2000);
				});
			}
			else
			{
				$(".error").html("Passwords are not matching.");
				$(".error").css('color','#d41812');
				return false;
			}
		});
	});
</script>
</head>

<body>
<div class="login-container">

<div style="display:block; float:left; width:100%; padding-bottom:27px;">

	<div class="login-logo"><img src="/images/jd-logo.png" align="absmiddle"/></div>
	
	<div class="login-box">
	<div class="msg forget-password"></div>
	<?php if ($this->msg == 'Success') { ?>
	<div id="">
			<form name="reset"  id="reset_form" >
			<div class="error">Reset Your Password Here</div>
		    <input name="pwd" id="pwd" type="password" placeholder="Password"  class="login-input"/>
		    <input name="repwd" id="repwd" type="password" placeholder="Re-Enter Password" class="login-input"/>
		    <img id="reset_Submit" class="reset-btn" />
			<input name="id"  type="hidden" value="<?php echo ($this->id); ?>"/>
			<input name="token"  type="hidden" value="<?php echo ($this->token); ?>"/>
			</form>
			
	 	<?php }
			else {
	 	?>
	 			<div class="error"><?php echo ($this->msg); ?></div>
	 	
	 	<?php } ?>
	 	</div>
	</div>
	<?php if ($this->msg == 'Success') { ?>
	<div class="login-box-info">
		<b>Password must Contain:</b>
		<ul>
			<li id="pwd-length">8 to 32 characters in length</li>
			<li id="pwd-upperlower">At least 1 lowercase and 1 uppercase letter</li>
			<li id="pwd-number">At least 1 number</li>
			<li id="pwd-special">At least 1 symbol (!@#$%^&()’[]“?+-/*)</li>
		</ul>
	</div>
	<?php } ?>
		 
      <div class="add-box"><a href="#"></a></div>
	
	</div>

</body>
</html>


